### PR TITLE
Kernel cleanups

### PR DESCRIPTION
**Pull request by schodet**
Here is some cleanups for the kernel tree. See issue #2.

### CODE REVIEW

**Comment by botbench** [comment]
Have you tested these with the rather fragile build scripts for the firmware in the lms2012/open_first folder?

**Comment by schodet** [comment]
Hum, no, good catch!

**Comment by botbench** [comment]
The trouble with those scripts is that they have no error checking at any stage, so if something fails, it will simply continue with the next step and make a giant mess of it all.  A Grand Unified Build Script (GUBS) would be preferable to the collection of loose scripts right now.

**Comment by botbench** [comment]
Perhaps it could be done with make and use targets for each part.

**Comment by botbench** [comment]
I'll make that a new issue :)

**Comment by schodet** [comment]
Here it is, branch updated.
Now I deleted the .config file in kernel directory as the right configuration is in open_first.

**Pull request merged**
